#!/bin/bash
set -e  # Exit immediately if any command fails
# Ensure the script is run as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root."
    exit 1
fi

apt update && apt upgrade -y

for file in "$PWD"/sbin/*; do cp "$file" /sbin && chmod +x "/sbin/$(basename "$file")"; done
